# Generated by Django 3.1.4 on 2021-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelPracticeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('Desc', models.CharField(max_length=100)),
                ('sal', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
